name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        
      - name: Extract and print Git hash
        run: |
              HASH=$(git rev-parse --short HEAD)
              echo "Short hash is: $HASH"
              echo "GIT_HASH=$HASH" >> $GITHUB_ENV
      
      - name: Trigger JitPack build
        run: |
                echo "Triggering JitPack build"
                echo "HASH DETAILS: $GIT_HASH"
            
                PACKAGES_URL="https://jitpack.io/com/github/thonsi/kotatsu-parsers/$GIT_HASH"
                PACKAGES_FILE="packages.txt"
                touch ${PACKAGES_FILE}
            
                # Try the URL 6 times before failing
                count=1
                until [[ $count -gt 6 ]] || grep -q build.log ${PACKAGES_FILE} ; do
                  echo "Attempt ${count}/6"
                  STATUS=$(curl -s -o packages.txt -w "%{http_code}" --max-time 900 ${PACKAGES_URL})
            
                  let count+=1
                  if [[ "${STATUS}" -gt 399 ]]; then
                    sleep 30
                  fi
                done
            
                echo "::group::Files Available"
                cat ${PACKAGES_FILE}
                echo "::endgroup::"
            
                if [[ ${STATUS} -gt 399 ]] ; then
                  echo "FAILURE: ${STATUS} response from JitPack"
                  exit 1 
                fi
        env:
          GIT_HASH: ${{ env.GIT_HASH }}
