name: Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          
      - name: Build with Gradle
        shell: bash
        run: |
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          ./gradlew PublishToMavenLocal --stacktrace
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'release-artifacts'
          path: '~/.m2/repository/'
